version: '3'

services:
  wheels_front:
    build:
      context: ../appolo_ma
      dockerfile: Dockerfile
    ports:
      - "61527:8080"  
    restart: always

  nginx:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: nginx:latest
    ports:
      - "81:80"  
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount the Nginx configuration file
      - ./certificados:/etc/nginx/ssl  # Mount SSL certificate and key files
    depends_on:
      - wheels_front  # Specify dependency on the Flutter app service
    restart: always