version: '3'
networks:
  front_network:
    driver: bridge


services:
  appolo_web:
    build:
      context: ../appolo_ma
      dockerfile: Dockerfile
    ports:
      - 61527:8083
    restart: always
    networks:
      - front_network
  proxy_front:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - 81:81
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount the Nginx configuration file
    depends_on:
      - appolo_web  
    networks:
      - front_network
    restart: always